const items = [
  {
    id: 1,
    department: "ＤＸソリューション部",
    product: "aki-doco（駐車場利用状況管理システム）",
    industry: "生活関連サービス業・娯楽業・観光業",
    technology: "AI",
    technical_details: "",
    state: "販売中",
    customer: "鹿児島空港、広島空港",
    cooperation_destination: "",
    sales_strategy: "",
    note: "",
    registration_date: "2021/7/20",
    update_date: "",
    changer: "山原\u3000豊",
    attachedFile: [],
    comment: [],
  },

  {
    id: 2,
    department: "ＤＸソリューション部",
    product: "pickture（遺失物管理システム）",
    industry: "生活関連サービス業・娯楽業・観光業",
    technology: "AI",
    technical_details: "",
    state: "販売中",
    customer: "うみたまご、トキハ",
    cooperation_destination: "",
    sales_strategy: "",
    note: "",
    registration_date: "2021/7/20",
    update_date: "",
    changer: "山原\u3000豊",
    attachedFile: [],
    comment: [],
  },

  {
    id: 3,
    department: "ＤＸソリューション部",
    product: "Health Checker ",
    industry: "医療・福祉",
    technology: "AI",
    technical_details: "",
    state: "販売中",
    customer: "",
    cooperation_destination: "",
    sales_strategy: "",
    note: "",
    registration_date: "2021/7/20",
    update_date: "",
    changer: "-",
    attachedFile: [],
    comment: [],
  },

  {
    id: 4,
    department: "ＤＸソリューション部",
    product: "ドローンサッカー",
    industry: "生活関連サービス業・娯楽業・観光業",
    technology: "ドローン",
    technical_details: "ドローン操縦、プログラ ミング",
    state: "会員募集中",
    customer: "",
    cooperation_destination: "オートバックスセブン",
    sales_strategy: "",
    note: "日本ドローンサッカー連盟",
    registration_date: "2021/7/20",
    update_date: "",
    changer: "-",
    attachedFile: [],
    comment: [],
  },

  {
    id: 5,
    department: "ＤＸソリューション部",
    product: "ＤＵＣＴ（ドローン飛行場所管理）",
    industry: "生活関連サービス業・娯楽業・観光業",
    technology: "ドローン",
    technical_details: "",
    state: "販売中",
    customer: "那賀町、館山他",
    cooperation_destination: "",
    sales_strategy: "",
    note: "",
    registration_date: "2021/7/20",
    update_date: "",
    changer: "-",
    attachedFile: [],
    comment: [],
  },

  {
    id: 6,
    department: "ＤＸソリューション部",
    product: "ＤＲＯＴＳ（ドローン講習オンライン実技テストシステム）",
    industry: "教育・学習支援業",
    technology: "ドローン,通信",
    technical_details: "",
    state: "販売中",
    customer: "",
    cooperation_destination: "",
    sales_strategy: "",
    note: "",
    registration_date: "2021/7/20",
    update_date: "",
    changer: "-",
    attachedFile: [],
    comment: [],
  },

  {
    id: 7,
    department: "ＤＸソリューション部",
    product: "ぷらっとワ～プ(オンライン観光システム)  ",
    industry: "生活関連サービス業・娯楽業・観光業",
    technology: "通信",
    technical_details: "",
    state: "販売中",
    customer: "",
    cooperation_destination: "",
    sales_strategy: "",
    note: "",
    registration_date: "2021/7/20",
    update_date: "",
    changer: "-",
    attachedFile: [],
    comment: [],
  },

  {
    id: 8,
    department: "ＤＸソリューション部",
    product: "デジタル商品券発行スキーム",
    industry: "金融業・保険業",
    technology: "Fintech",
    technical_details: "",
    state: "検討中",
    customer: "大分銀行連携",
    cooperation_destination: "",
    sales_strategy: "",
    note: "",
    registration_date: "2021/7/20",
    update_date: "",
    changer: "-",
    attachedFile: [],
    comment: [],
  },

  {
    id: 9,
    department: "ＤＸソリューション部",
    product: "タグアシスト",
    industry: "医療・福祉",
    technology: "IoT",
    technical_details: "",
    state: "販売中",
    customer: "太陽の家",
    cooperation_destination: "",
    sales_strategy: "",
    note: "",
    registration_date: "2021/7/20",
    update_date: "",
    changer: "-",
    attachedFile: [],
    comment: [],
  },

  {
    id: 10,
    department: "ＤＸソリューション部",
    product: "「光センシング」技術を用いた病理診断支 援",
    industry: "医療・福祉",
    technology: "AI",
    technical_details: "",
    state: "開発中",
    customer: "大分大学、徳島大学",
    cooperation_destination: "",
    sales_strategy: "",
    note: "",
    registration_date: "2021/7/20",
    update_date: "",
    changer: "-",
    attachedFile: [],
    comment: [],
  },

  {
    id: 11,
    department: "ソリューションサービス部",
    product: "eG-Resource（環境情報ソリューション）",
    industry: "公務",
    technology: "IoT",
    technical_details: "",
    state: "販売中",
    customer: "",
    cooperation_destination: "",
    sales_strategy: "",
    note: "",
    registration_date: "2021/7/20",
    update_date: "",
    changer: "-",
    attachedFile: [],
    comment: [],
  },

  {
    id: 12,
    department: "ＤＸソリューション部",
    product: "シセン",
    industry: "医療・福祉",
    technology: "AI",
    technical_details: "",
    state: "開発中",
    customer: "",
    cooperation_destination: "",
    sales_strategy: "",
    note: "ＤＸ最優秀",
    registration_date: "2021/7/20",
    update_date: "",
    changer: "-",
    attachedFile: [],
    comment: [],
  },

  {
    id: 13,
    department: "ライフソリューション部",
    product: "電子カルテのテキストマイニング",
    industry: "医療・福祉",
    technology: "AI",
    technical_details: "",
    state: "販売中",
    customer: " 肥前精神医療センター",
    cooperation_destination: "",
    sales_strategy: "",
    note: "",
    registration_date: "2021/7/20",
    update_date: "",
    changer: "-",
    attachedFile: [],
    comment: [],
  },

  {
    id: 14,
    department: "デジタルイノベーション推進部",
    product: "粗大ゴミ画像認識API ",
    industry: "公務",
    technology: "AI",
    technical_details: "",
    state: "販売中",
    customer: "",
    cooperation_destination: "",
    sales_strategy: "",
    note: "販売代理店契約準 備・富士通Japan（大阪）経由での提案依頼対応中",
    registration_date: "2021/7/20",
    update_date: "",
    changer: "-",
    attachedFile: [],
    comment: [],
  },

  {
    id: 15,
    department: "福岡支社",
    product: "車両床下撮影検査システム",
    industry: "運輸業・郵便業",
    technology: "AI",
    technical_details: "",
    state: "販売・検討・開発中止",
    customer: "JR九州エンジニアリング株式会社",
    cooperation_destination: "",
    sales_strategy: "",
    note: "2021年 度事業は、予算の関係で見送り",
    registration_date: "2021/9/21",
    update_date: "",
    changer: "",
    attachedFile: [],
    comment: [],
  },

  {
    id: 16,
    department: "福岡支社",
    product: "新幹線屋根上検査システム構築",
    industry: "運輸業・郵便業",
    technology: "AI",
    technical_details: "",
    state: "販売・検討・開発中止",
    customer: "JR九州エンジニアリング株式会社",
    cooperation_destination: "",
    sales_strategy: "",
    note: "8/31提案書提出、9/10プレゼン、9/18他社に決定",
    registration_date: "2021/9/21",
    update_date: "",
    changer: "",
    attachedFile: [],
    comment: [],
  },

  {
    id: 17,
    department: "福岡支社",
    product: "電子申請支援システムのガイド機能構築",
    industry: "公務",
    technology: "IoT",
    technical_details: "",
    state: "検討中",
    customer: "大牟田市",
    cooperation_destination: "",
    sales_strategy: "",
    note: "2021年6月議会では運用経費が高いため財政査定で落とされた。",
    registration_date: "2021/9/21",
    update_date: "",
    changer: "",
    attachedFile: [],
    comment: [],
  },

  {
    id: 18,
    department: "ＤＸソリューション部",
    product: "カーボンマネジメント",
    industry: "製造業",
    technology: "クラウド",
    technical_details: "",
    state: "検討中",
    customer: "ジャパンラーニング",
    cooperation_destination: "",
    sales_strategy: "",
    note: "共創企画",
    registration_date: "2021/9/21",
    update_date: "",
    changer: "山原\u3000豊",
    attachedFile: [],
    comment: [],
  },

  {
    id: 19,
    department: "ＤＸソリューション部",
    product: "チャットナースコール",
    industry: "医療・福祉",
    technology: "AI,クラウド",
    technical_details: "",
    state: "検討中",
    customer: "ア イホン",
    cooperation_destination: "",
    sales_strategy: "",
    note: "共創企画",
    registration_date: "2021/9/21",
    update_date: "",
    changer: "山原\u3000豊",
    attachedFile: [],
    comment: [],
  },

  {
    id: 20,
    department: "ソリューション営業部",
    product: "LGWANサービス（プロジェクト管理・無害化ソリューション）",
    industry: "公務",
    technology: "クラウド",
    technical_details: "",
    state: "検討中",
    customer: "全国自治体",
    cooperation_destination: "",
    sales_strategy: "",
    note: "中央区CIO補佐官との情報交換より発案。各メーカと調整中",
    registration_date: "2021/9/21",
    update_date: "2021/9/21",
    changer: "塩月\u3000輝",
    attachedFile: [],
    comment: [],
  },

  {
    id: 21,
    department: "ライフソリューション部",
    product: "介護業務見える化システム\u3000Care See",
    industry: "医療・福祉",
    technology: "クラウド",
    technical_details: "",
    state: "検討中",
    customer: "大分県福祉保健部",
    cooperation_destination: "",
    sales_strategy: "",
    note: "",
    registration_date: "2021/10/18",
    update_date: "2021/10/18",
    changer: "大石\u3000竜也",
    attachedFile: [],
    comment: [],
  },

  {
    id: 22,
    department: "ソリューションサービス部",
    product: "ごみ収集支援ナビゲーションシステム",
    industry: "生活関連サービス業・娯楽業・観光業",
    technology: "IoT,通信",
    technical_details: "",
    state: "開発中",
    customer: "ごみ収集事業者",
    cooperation_destination: "",
    sales_strategy: "",
    note: "",
    registration_date: "2021/10/29",
    update_date: "2021/10/29",
    changer: "",
    attachedFile: [],
    comment: [],
  },

  {
    id: 23,
    department: "デジタルイノベーション推進部",
    product: "PUSH型リアルタイムWEBオークションシステム構築",
    industry: "サービス業(他に分類されないもの)",
    technology: "通信,クラウド",
    technical_details:
      "オークション残り時間や入札金額などすべての情報をサーバーからPUSHすることで、会場オークション並みの臨場感を実現。\nAWS、WebSocket、node.js、YoutubeLive等",
    state: "販売中",
    customer: "株式会社オークネット",
    cooperation_destination: "",
    sales_strategy: "要素技術を使った他システム展開をAUBA上で行う予定。",
    note: "",
    registration_date: "2021/11/10",
    update_date: "2021/11/10",
    changer: "",
    attachedFile: [],
    comment: [],
  },

  {
    id: 24,
    department: "デジタルイノベーション推進部",
    product: "次世代ドラレコサービス基盤",
    industry: "製造業",
    technology: "IoT,5G,クラウド",
    technical_details:
      "クラウド上からドラレコデ ータ（動画、センサー）へのアクセスを可能とするサービスの開発。\nAWS IoT、MQTT、SORACOM、5G、IaC等",
    state: "検討中",
    customer: "株式会社カーメイト",
    cooperation_destination: "",
    sales_strategy: "",
    note: "",
    registration_date: "2021/11/10",
    update_date: "2021/11/10",
    changer: "",
    attachedFile: [],
    comment: [],
  },

  {
    id: 25,
    department: "ソリューションサービス部",
    product: "ごみ収集支援ナビゲーションシステム",
    industry: "公務",
    technology: "IoT",
    technical_details:
      "・一般 家庭ごみ収集（可燃ごみや資源ごみなどのパッカー車等による巡回収集）を支援する専用ナビゲーションシステム。\n・一般的なカーナビとは異なり、「目的地付近」までのナビゲーションではなく、「目的地まで確実に」ナビゲーションを行う。\n・わかりやすいナビ画面（今どこを走っていて、次はどこを右左折・Uターンしなけ ればならないのかがわかる）に加え、\n\u3000音声ガイダンスも一般的なカーナビと同様に行う。\n・一般的なカーナビは、カーナビメーカーが提供する道路データ（交差点等の情報）を元にナビゲーションを行うが、\n\u3000本ナビゲーションシステムは、管理者が指定したコースをナビゲーションするため、道路データの無い施設内のナビゲーション等も可能。\n・ナビゲーション用データの受信は無線(Wi-Fi)経由で行うため、通信ＳＩＭ 等は不要（ランニングコスト０）",
    state: "販売中",
    customer: "瀬戸市",
    cooperation_destination: "ソリューションサービス部",
    sales_strategy: "",
    note: "2022年4月より瀬戸市で運用開始。運用によ る収集漏れなし。",
    registration_date: "2022/8/29",
    update_date: "2022/8/29",
    changer: "中村\u3000健一郎",
    attachedFile: [],
    comment: [],
  },

  {
    id: 26,
    department: "ソリューションサービス部",
    product: "粗大ごみ等収集支援タブレットシステ ム（Windows版）",
    industry: "公務",
    technology: "IoT",
    technical_details:
      "・粗大ごみの収集を支援するタブレットシステム\n・カーナビ機能とシームレスな連携を実現\n・独 自アルドリズムにより収集担当者が毎日実施していた走行計画の完全自動化を実現\n\u3000※走行ルートの最適 化機能は、多くのカーナビメーカーは最大３０件程度だが、\n\u3000\u3000独自アルゴリズムにより、最大を撤廃\n",
    state: "販売中",
    customer: "瀬戸市",
    cooperation_destination: "ソリューションサービス部",
    sales_strategy: "",
    note: "2022年4月より瀬戸市で運用開始。事前計画を行う必要がなくなり、収集 作業時間も短縮している。",
    registration_date: "2022/8/29",
    update_date: "2022/8/29",
    changer: "中村\u3000健一郎",
    attachedFile: [],
    comment: [],
  },

  {
    id: 27,
    department: "ソリューションサービス部",
    product: "臨時ごみ等収集支援タブレットシステ ム（Windows版）",
    industry: "公務",
    technology: "IoT",
    technical_details:
      "・臨時ごみ、災害ごみ等の収集を支援するタブレットシステム\n・カーナビ機能とシームレスな連携 を実現\n・収集現場への直接の収集指示が行え、その場所までのナビを行うことで、当日発生する各種ごみの\n\u3000収集指示を実現\n・収集車両への各種メッセージを行うことができ、現場の写真などもリアルタイムで共有することが可能\n※本システムにより、収集担当はセンターに次の収集場所の情報を貰いに戻る必要がなくな るため、\n\u3000収集効率の大幅な向上を実現",
    state: "販売中",
    customer: "瀬戸市",
    cooperation_destination: "ソリューションサービス部",
    sales_strategy: "",
    note: "2022年4月より瀬戸市で運用開 始。",
    registration_date: "2022/8/29",
    update_date: "2022/8/29",
    changer: "中村\u3000健一郎",
    attachedFile: [],
    comment: [],
  },

  {
    id: 28,
    department: "ソリューションサービス部",
    product: "IoT-Gateway\u3000：\u3000ＧＲＥＩＦ（グライフ）",
    industry: "サービス業(他に分類されないもの)",
    technology: "IoT",
    technical_details:
      "・ＯＥＣ初のオリジナルハードウェア\n・単体で屋外設置可能なIoT-Gateway\n・標準で以下の機能を 実装\n\u3000①太陽光発電対応\n\u3000②ＤＣ１２～２４Ｖ対応\n\u3000③アナログセンサー対応\n\u3000④デジタルセンサー対応\n\u3000⑤入力電圧と同じ電圧迄のデジタルセンサー使用可能\n\u3000⑥Bluetooth4.2対応\n\u3000⑦Wi-Fi送受信機能\n\u3000⑧LTE通信機能（Docomo系通信SIM）\n\u3000⑨オプションでWi-SUN通信に対応\n\u3000⑩GNSS標準実装（みちびきのサブメータ補正対応）\n\u3000⑪GNSSによる時刻補正機能あり\n\u3000⑫温度、気 圧、加速度センサー内蔵\n\u3000⑬オリジナルＯＴＡ(Over The Air）機能標準搭載\u3000・・・\u3000特許取得技術\n",
    state: "販売中",
    customer: "合同会社シンセイ",
    cooperation_destination: "ソリューションサービス部",
    sales_strategy: "",
    note: "",
    registration_date: "2022/8/29",
    update_date: "2022/8/29",
    changer: "中村\u3000健一郎",
    attachedFile: [],
    comment: [],
  },
];

export default items;
