const datas = [
  {
    id: 1,
    registrationDate: "2021/7/20",
    updateDate: "2021/9/22",
    changer: "佐藤亜紀",
    department: "総務部",
    work: "名刺作成",
    supportTool: "Excel",
    state: "運用中",
    staff: "伊藤理事",
    expectedEffect:
      "人事奉行からのデータ取り込みにより、所属部署、役職等、データの一括変更が行えるようになった。入力ミスが減り、工数も減る事となった。",
    effect: "中",
    attachedFile: "",
    comment: [],
  },
  {
    id: 2,
    registrationDate: "2021/7/20",
    updateDate: "2021/9/21",
    changer: "佐藤亜紀",
    department: "総務部",
    work: "社員名簿自動作成",
    supportTool: "UiPath、Excel",
    state: "運用中",
    staff: "伊藤理事",
    expectedEffect:
      "人事奉行からのデータ取り込みにより、データの一括変更が行えるようになった。入力ミスが減り、工数も減る事となった。",
    effect: "中",
    attachedFile: "",
    comment: [],
  },
  {
    id: 3,
    registrationDate: "2021/7/20",
    updateDate: "2021/9/24",
    changer: "-",
    department: "総務部",
    work: "社員構成図自動作成（年齢別、社歴別）",
    supportTool: "Excel",
    state: "運用中",
    staff: "伊藤理事",
    expectedEffect:
      "今迄は人事情報を元に手入力で更新していたが、人事奉行のデータを元に自動で作成する事が出来るようになった為、作業時間のかなりの削減となった。また、入力ミスが無くなったことによる、データの正確性も上がった。",
    effect: "中",
    attachedFile: "",
    comment: [],
  },
  {
    id: 4,
    registrationDate: "2021/7/20",
    updateDate: "2021/9/27",
    changer: "-",
    department: "総務部",
    work: "サイボウズメッセージ自動送信（部門別、個人別、一括）",
    supportTool: "Excel、UiPath",
    state: "運用中",
    staff: "伊藤理事",
    expectedEffect:
      "様々な調査、分析、処理結果をサイボウズを使って、関係する部門や個人あるいは対象者全員にメール配信する機能。\n作業の効率化に繋がる。",
    effect: "中",
    attachedFile: "",
    comment: [],
  },
  {
    id: 5,
    registrationDate: "2021/7/20",
    updateDate: "2021/9/27",
    changer: "上野佐智子",
    department: "総務部",
    work: "残業60時間超過者抽出＆連絡（安全衛生委員会）",
    supportTool: "Excel、UiPath",
    state: "運用中",
    staff: "伊藤理事",
    expectedEffect:
      "交通安全衛生委員会用に、毎月の残業60時間オーバーの方を抽出し、対象者のいる部門あるいは対象者個人通知、連絡する機能。",
    effect: "",
    attachedFile: "",
    comment: [],
  },
  {
    id: 6,
    registrationDate: "2021/7/20",
    updateDate: "2021/9/27",
    changer: "上野佐智子",
    department: "総務部",
    work: "健康診断支援（予約、結果集計、請求仕訳）",
    supportTool: "Excel",
    state: "運用中",
    staff: "伊藤理事",
    expectedEffect:
      "定期健康診断の対象者名簿の作成から予約割り振り、健診結果の取込みと管理までを行う。入力作業等の工数削減及び入力ミスが減り、効率化に繋がった。",
    effect: "大",
    attachedFile: "",
    comment: [],
  },
  {
    id: 7,
    registrationDate: "2021/7/20",
    updateDate: "2021/9/27",
    changer: "上野佐智子",
    department: "総務部",
    work: "経費精算書作成",
    supportTool: "Excel",
    state: "運用中",
    staff: "伊藤理事",
    expectedEffect:
      "財務部へ渡す様々な経費精算書を作成する。作業の効率化・正確さが期待できる。",
    effect: "中",
    attachedFile: "",
    comment: [],
  },
  {
    id: 8,
    registrationDate: "2021/7/20",
    updateDate: "2021/9/27",
    changer: "上野佐智子",
    department: "総務部",
    work: "生命保険料管理",
    supportTool: "Excel",
    state: "運用中",
    staff: "伊藤理事",
    expectedEffect:
      "生命保険料の保険料額を管理するエクセルの運用を簡単にするための変更を行っている。",
    effect: "",
    attachedFile: "",
    comment: [],
  },
  {
    id: 9,
    registrationDate: "2021/7/20",
    updateDate: "2021/9/27",
    changer: "-",
    department: "総務部",
    work: "出張伺い 抽出",
    supportTool: "UiPath、Excel",
    state: "運用中",
    staff: "伊藤理事",
    expectedEffect:
      "災害対策の1つで、日本国内で地 震が発生した場合に対象地域へ出張している人がいるか確認しフォローするためのものであった。しかしながら、出張伺いがサイボウズからPowerEggへ変わったため、現在利用できない状況です。",
    effect: "",
    attachedFile: "",
    comment: [],
  },
  {
    id: 10,
    registrationDate: "2021/7/20",
    updateDate: "2021/9/24",
    changer: "佐藤一生",
    department: "総務部",
    work: " 電力ﾚﾎﾟｰﾄ出力",
    supportTool: "UiPath",
    state: "運用中",
    staff: "伊藤理事",
    expectedEffect:
      "・作業手順の簡素化・時間の短縮、作業手順書の30ページが6ページとなり、作業時間が96分から6分に短縮（データの確認や計算結果の検証等の作業時間を除く）検針時の指針の読み誤り・転記ミスが解消された。",
    effect: "中",
    attachedFile: "",
    comment: [],
  },
  {
    id: 11,
    registrationDate: "2021/7/20",
    updateDate: "2021/9/13",
    changer: "高橋佑輔",
    department: "人事部",
    work: " リファラル採用ツール利用",
    supportTool: "My Refer",
    state: "運用中",
    staff: "高橋佑輔",
    expectedEffect:
      "紹介までのフロ ー、紹介後のフローそれぞれを全てシステム上で一元管理することにより、リファラル採用にかかる工数を削減することができる。",
    effect: "中",
    attachedFile: "",
    comment: [],
  },
  {
    id: 12,
    registrationDate: "2021/7/20",
    updateDate: "2021/9/21",
    changer: "川野 裕貴",
    department: "人事部",
    work: "業務組織＆組織体制図自動作成",
    supportTool: "Excel",
    state: "運用中",
    staff: "伊藤理事",
    expectedEffect:
      "新年度組織の体制図作成を自動化することで手作業でしていた部分の工数削減と誤登録の防止に繋がっている。",
    effect: "中",
    attachedFile: "",
    comment: [],
  },
  {
    id: 13,
    registrationDate: "2021/7/20",
    updateDate: "2021/9/21",
    changer: "川野 裕貴",
    department: "人事部",
    work: "年度当初人事発令自動作成",
    supportTool: "Excel",
    state: "運用中",
    staff: "伊藤理事",
    expectedEffect:
      "年度当初の全社員分の人事発令を組織体制図から自動作成するため、手作業でしていた部分の工数削減とご入力の防止に繋がっている。",
    effect: "",
    attachedFile: "",
    comment: [],
  },
  {
    id: 14,
    registrationDate: "2021/7/20",
    updateDate: "2021/9/21",
    changer: "川野 裕貴",
    department: "人事部",
    work: "年度当初人事奉行異動ﾃﾞｰﾀ自動作成",
    supportTool: "Excel",
    state: "運用中",
    staff: "伊藤理事",
    expectedEffect:
      "全社員の異動情報を組織体制図から自動作成するため、手入力による工数の削減と誤登録の防止に繋がっている。",
    effect: "中",
    attachedFile: "",
    comment: [],
  },
  {
    id: 15,
    registrationDate: "2021/7/20",
    updateDate: "2021/9/27",
    changer: "末髙\u3000成史",
    department: "人事部",
    work: "給与改定支援",
    supportTool: "Excel",
    state: "計画・調査中",
    staff: "伊藤理事",
    expectedEffect:
      "キャリアステージ体系の改定途中であり、給与テーブルが完全に固まるまで一旦保留中。",
    effect: "--",
    attachedFile: "",
    comment: [],
  },
  {
    id: 16,
    registrationDate: "2021/7/20",
    updateDate: "2021/9/21",
    changer: "川野 裕貴",
    department: "人事部",
    work: "勤務表（正社員、嘱託社員）",
    supportTool: "Excel",
    state: "運用中",
    staff: "伊藤理事",
    expectedEffect:
      "一部の特殊な勤務地のみ適用中。エラーチェック機能や入力制限による誤入力防止によりエラーデータの削減に繋がっている。",
    effect: "中",
    attachedFile: "",
    comment: [],
  },
  {
    id: 17,
    registrationDate: "2021/7/20",
    updateDate: "2021/9/21",
    changer: "川野 裕貴",
    department: "人事部",
    work: "勤務表取込＆奉行連携ﾃﾞｰﾀ作成（正社員、嘱託社員）",
    supportTool: "Excel",
    state: "運用中",
    staff: "伊藤理事",
    expectedEffect:
      "勤務表から手計算していた勤怠情報を正しく集計・取り込みすることができる。",
    effect: "中",
    attachedFile: "",
    comment: [],
  },
  {
    id: 18,
    registrationDate: "2021/7/20",
    updateDate: "2021/9/21",
    changer: "後藤\u3000恵",
    department: "人事部",
    work: "給与計算後ﾃﾞｰﾀ抽出（正社員、嘱託社員）",
    supportTool: "UiPath、Excel",
    state: "運用中",
    staff: "伊藤理事",
    expectedEffect:
      "手作業で行っていた給与後処理(経営戦略部へ送付分)の作業を自動化し、作業工数の削減に繋がっている。",
    effect: "中",
    attachedFile: "",
    comment: [],
  },
  {
    id: 19,
    registrationDate: "2021/7/20",
    updateDate: "2021/9/21",
    changer: "川野 裕貴",
    department: "人事部",
    work: "勤務表（臨時社員、ﾊﾟｰﾄ社員）",
    supportTool: "Excel",
    state: "運用中",
    staff: "伊藤理事",
    expectedEffect:
      "エラーチェック機能や入力制限による誤入力防止によりエラーデータの削減に繋がっている。",
    effect: "中",
    attachedFile: "",
    comment: [],
  },
  {
    id: 20,
    registrationDate: "2021/7/20",
    updateDate: "2021/9/21",
    changer: "川野 裕貴",
    department: "人事部",
    work: "勤務表取込＆奉行連携ﾃﾞｰﾀ作成（臨時社員、ﾊﾟｰﾄ社員）",
    supportTool: "Excel",
    state: "運用中",
    staff: "伊藤理事",
    expectedEffect:
      "勤務表から手計算していた勤怠情報を正しく集計・取り込みすることができる。",
    effect: "中",
    attachedFile: "",
    comment: [],
  },
  {
    id: 21,
    registrationDate: "2021/7/20",
    updateDate: "2021/9/21",
    changer: "川野 裕貴",
    department: "人事部",
    work: "給与計算（臨時社員、ﾊﾟｰﾄ社員）",
    supportTool: "Excel",
    state: "運用中",
    staff: "伊藤理事",
    expectedEffect:
      "手作業でしていた給与計算Excelの明細作成や年度更新などの作業を自動化し、月初の作業工数の削減に繋がっている。",
    effect: "中",
    attachedFile: "",
    comment: [],
  },
  {
    id: 22,
    registrationDate: "2021/7/20",
    updateDate: "2021/9/21",
    changer: "川野 裕貴",
    department: "人事部",
    work: "勤怠自動ﾁｪｯｸ＆連絡",
    supportTool: "UiPath、Excel",
    state: "運用中",
    staff: "伊藤理事",
    expectedEffect:
      "月初の勤怠データのエラーチェック及び各部門へのエラー連絡を自動化することで、約1人日かかっていた作業が2人時程度にまで削減できる。",
    effect: "大",
    attachedFile: "",
    comment: [],
  },
  {
    id: 23,
    registrationDate: "2021/7/20",
    updateDate: "2021/9/21",
    changer: "後藤\u3000恵",
    department: "人事部",
    work: "通勤費データ管理(給与データ作成)",
    supportTool: "Excel",
    state: "運用中",
    staff: "伊藤理事",
    expectedEffect:
      "これま で手作業で行っていた通勤費データを、金額入力後の作業を自動化。同excel内で前月との比較も行い、変更があった社員分を給与へ流し込み を行う事により、時間の削減にも繋がっている。\n",
    effect: "中",
    attachedFile: "",
    comment: [],
  },
  {
    id: 24,
    registrationDate: "2021/7/20",
    updateDate: "2021/9/14",
    changer: "井戸量敏",
    department: "経営戦略部",
    work: "常勤役員会ペーパーレス化",
    supportTool: "moreNOTE",
    state: "準備・検証中",
    staff: "井戸量敏",
    expectedEffect: "会議時のペーパレス",
    effect: "",
    attachedFile: "",
    comment: [],
  },
  {
    id: 25,
    registrationDate: "2021/7/20",
    updateDate: "2021/9/9",
    changer: "森脇毅",
    department: "経営戦略部",
    work: "バージョン管理標準化",
    supportTool: "GitHub、GitLab",
    state: "準備・検証中",
    staff: "若林推進",
    expectedEffect:
      "開発業 務において、プログラムのバージョン管理を標準化する事ができる。",
    effect: "",
    attachedFile: "",
    comment: [],
  },
  {
    id: 26,
    registrationDate: "2021/7/20",
    updateDate: "2021/9/14",
    changer: "森脇毅",
    department: "経営戦略部",
    work: "用紙量計測、在庫チェック",
    supportTool: "スマートマット",
    state: "運用見送り",
    staff: "BPO推進部",
    expectedEffect:
      "プリンターの用紙が無くなる前に、残量が少なくなっているのを認知できる。",
    effect: "",
    attachedFile: "",
    comment: [],
  },
  {
    id: 27,
    registrationDate: "2021/7/20",
    updateDate: "2021/9/9",
    changer: "相川真理子",
    department: "経営戦略部",
    work: "議事録作成支援",
    supportTool: "Ami Voice、COTOHA、スマート書記",
    state: "運用見送り",
    staff: "相川真理子",
    expectedEffect:
      "発言の聞き直しが楽であった。所要時間が短くなる。\n発言をまとめるというところまでの機能はない。\nオンライン会議の録音においては、AmiVoiceが最も使いやすかった。\n",
    effect: "",
    attachedFile: "",
    comment: [],
  },
  {
    id: 28,
    registrationDate: "2021/7/20",
    updateDate: "2021/9/14",
    changer: "井戸量敏",
    department: "経営戦略部",
    work: "マーケティング、トレンド検索支援",
    supportTool: "Astrategy",
    state: "運用中",
    staff: "井戸量敏",
    expectedEffect:
      "市 場動向や競合の動きを把握できる。\n製品やキーワードでの情報収集が可能で、提案書や営業情報の収集に役立つ",
    effect: "中",
    attachedFile: "",
    comment: [],
  },
  {
    id: 29,
    registrationDate: "2021/7/20",
    updateDate: "2021/9/9",
    changer: "森脇毅",
    department: "経営戦略部",
    work: "未収前受処理改善",
    supportTool: "Excel",
    state: "計画・調査中",
    staff: "伊藤理事",
    expectedEffect: "未収前受処理が簡単になる。所要時間が短くなる。",
    effect: "",
    attachedFile: "",
    comment: [],
  },
  {
    id: 30,
    registrationDate: "2021/7/20",
    updateDate: "2022/1/11",
    changer: "木津玲子",
    department: "経営戦略部",
    work: "工数実績および人件費配分の処理改善",
    supportTool: "Excel",
    state: "運用中",
    staff: "伊藤理事",
    expectedEffect:
      "工数 実績および人件費配分処理の所要時間が、通常の三分の一程度になった。",
    effect: "中",
    attachedFile: "",
    comment: [],
  },
  {
    id: 31,
    registrationDate: "2021/7/20",
    updateDate: "2021/9/14",
    changer: "井戸量敏",
    department: "経営戦略部",
    work: "事業の見える化",
    supportTool: "UiPath、Excel",
    state: "計画・調査中",
    staff: "伊藤理事",
    expectedEffect: "事業戦略に 利用",
    effect: "",
    attachedFile: "",
    comment: [],
  },
  {
    id: 32,
    registrationDate: "2021/7/20",
    updateDate: "2021/9/7",
    changer: "麻生良哉",
    department: "財務部",
    work: "経費精算システム",
    supportTool: "POWER EGG",
    state: "運用中",
    staff: "財務部",
    expectedEffect:
      "従来の紙からＰＯＷＥＲＥＧＧに移行。作業効率、データベース化、将来のペーパーレス化に近付いた。",
    effect: "中",
    attachedFile: "",
    comment: [],
  },
  {
    id: 33,
    registrationDate: "2021/7/20",
    updateDate: "2021/9/7",
    changer: "麻生良哉",
    department: "財務部",
    work: "経費精算ﾃﾞｰﾀの勘定奉行取込み",
    supportTool: "Excel",
    state: "運用中",
    staff: "伊藤理事",
    expectedEffect: "9/1本稼働、問題 なく推移中。",
    effect: "中",
    attachedFile: "",
    comment: [],
  },
  {
    id: 34,
    registrationDate: "2021/7/20",
    updateDate: "2021/9/7",
    changer: "麻生良哉",
    department: "財務部",
    work: "売上伝票管理",
    supportTool: "Excel",
    state: "運用中",
    staff: "伊藤理事",
    expectedEffect: "手作業集計をマクロで時間短縮が図られた。",
    effect: "中",
    attachedFile: "",
    comment: [],
  },
  {
    id: 35,
    registrationDate: "2021/7/20",
    updateDate: "2021/9/7",
    changer: "麻生良哉",
    department: "財務部",
    work: "消費税仮払金ﾁｪｯｸ",
    supportTool: "Excel",
    state: "運用中",
    staff: "伊藤理事",
    expectedEffect:
      "目視チェックからマクロでのデータチェックで作業時間短縮、正確性向上が図られた。",
    effect: "中",
    attachedFile: "",
    comment: [],
  },
  {
    id: 36,
    registrationDate: "2021/7/20",
    updateDate: "2021/9/7",
    changer: "麻生良哉",
    department: "財務部",
    work: "当初予算表の自動集計",
    supportTool: "Excel",
    state: "運用中",
    staff: "伊藤理事",
    expectedEffect: "タイトな予算作成期間を同システムで時間短縮できた。",
    effect: "大",
    attachedFile: "",
    comment: [],
  },
  {
    id: 37,
    registrationDate: "2021/7/20",
    updateDate: "2021/9/7",
    changer: "麻生良哉",
    department: "財務部",
    work: "予算実績表の自動集計",
    supportTool: "Excel",
    state: "運用中",
    staff: "伊藤理事",
    expectedEffect: "手入力から自動入力により作業の大幅削減につながった。",
    effect: "大",
    attachedFile: "",
    comment: [],
  },
  {
    id: 38,
    registrationDate: "2021/7/20",
    updateDate: "2021/9/7",
    changer: "麻生良哉",
    department: "財務部",
    work: "売上確定処理改善",
    supportTool: "Excel",
    state: "運用中",
    staff: "伊藤理事",
    expectedEffect:
      "月次予算実績へのリンクをマクロに変更。リンクによるずれ等のリスクが低減された。",
    effect: "中",
    attachedFile: "",
    comment: [],
  },
  {
    id: 39,
    registrationDate: "2021/9/13",
    updateDate: "2022/1/7",
    changer: "森脇毅",
    department: "経営戦略部",
    work: "自主開発パッケージの回収状況の見える化",
    supportTool: "Excel、他",
    state: "準備・検証中",
    staff: "金江、森脇",
    expectedEffect:
      "単に回収を促すだけでなく、回収状況の見える化が可能になる。",
    effect: "",
    attachedFile: "",
    comment: [],
  },
  {
    id: 40,
    registrationDate: "2021/9/13",
    updateDate: "2021/9/13",
    changer: "金江博文",
    department: "経営戦略部",
    work: "外注管理（契約、請求）業務の改善",
    supportTool: "AI-OCR、RPA、Excel、他",
    state: "計画・調査中",
    staff: "",
    expectedEffect: "",
    effect: "",
    attachedFile: "",
    comment: [],
  },
  {
    id: 41,
    registrationDate: "2021/9/14",
    updateDate: "2021/9/14",
    changer: "金江博文",
    department: "経営戦略部",
    work: "プロジェクト開発資料管理",
    supportTool: "AI-OCR、RPA、Excel、他",
    state: "計画・調査中",
    staff: "",
    expectedEffect: "",
    effect: "",
    attachedFile: "",
    comment: [],
  },
  {
    id: 42,
    registrationDate: "2021/9/15",
    updateDate: "2021/9/15",
    changer: "麻生良哉",
    department: "財務部",
    work: " 請求書の電子化（受領）",
    supportTool: "Bill One(㈱Sansan）",
    state: "運用中",
    staff: "財務部",
    expectedEffect: "事務の効率化、ペーパーレス化、改正法対応",
    effect: "中",
    attachedFile: "",
    comment: [],
  },
  {
    id: 43,
    registrationDate: "2021/9/21",
    updateDate: "2021/9/21",
    changer: "川野 裕貴",
    department: "人事部",
    work: "タレントマネジメントシステムのリプレース",
    supportTool: "タレントパレット",
    state: "準備・検証中",
    staff: "川野裕貴",
    expectedEffect:
      "タレントマネジメントシステムをカオナビからタレントパレットにリプレースすることにより、これまで活用できていなかっ た蓄積データを視覚的に集計・分析することができるようになる。",
    effect: "",
    attachedFile: "",
    comment: [],
  },
  {
    id: 44,
    registrationDate: "2021/9/21",
    updateDate: "2021/9/21",
    changer: "菅\u3000聡志",
    department: "インフラビジネス推進部",
    work: "DialPadの導入",
    supportTool: "DialPad",
    state: "運用中",
    staff: "",
    expectedEffect:
      "導入することに より、意図した相手に直接連絡を取ることができ(PC/スマホで受信可能)、チャット機能も使えるためメッセージを残すことも可能。外線から かけて内線で回す手間がなくなり、電話での対応効率化が望める。",
    effect: "中",
    attachedFile: "",
    comment: [],
  },
  {
    id: 45,
    registrationDate: "2021/9/21",
    updateDate: "2021/9/21",
    changer: "菅\u3000聡志",
    department: "インフラビジネス推進部",
    work: "Redmineの導入",
    supportTool: "Redmine",
    state: "運用中",
    staff: "",
    expectedEffect:
      "社内・顧客との 課題管理/作業依頼をチケットで行うことによって項目ごとに進捗具合などの管理ができる。",
    effect: "中",
    attachedFile: "",
    comment: [],
  },
  {
    id: 46,
    registrationDate: "2021/9/21",
    updateDate: "2021/9/21",
    changer: "佐藤\u3000匡",
    department: "BPO推進部",
    work: "用紙量計測、在庫チェック",
    supportTool: "Smartmat",
    state: "準備・検証中",
    staff: "BPO推進部BPO推進Gr",
    expectedEffect: "毎月末の目視確認の軽減、用紙発注の忘却防止\n",
    effect: "中",
    attachedFile: "",
    comment: [],
  },
  {
    id: 47,
    registrationDate: "2021/9/21",
    updateDate: "2021/9/21",
    changer: "佐藤\u3000匡",
    department: "BPO推進部",
    work: "outlookメール自動化",
    supportTool: "Python,anaconda",
    state: "計画・調査中",
    staff: "BPO推進部BPO推進Gr",
    expectedEffect: "忘却防止、電話連絡の削減\n",
    effect: "",
    attachedFile: "",
    comment: [],
  },
  {
    id: 48,
    registrationDate: "2021/9/21",
    updateDate: "2021/9/21",
    changer: "佐藤\u3000匡",
    department: "BPO推進部",
    work: "議事録書記",
    supportTool: "AI（自然言語処理）",
    state: "計画・調査中",
    staff: "BPO推進部BPO推進Gr",
    expectedEffect: "作業時間短縮\n",
    effect: "",
    attachedFile: "",
    comment: [],
  },
  {
    id: 49,
    registrationDate: "2021/9/21",
    updateDate: "2021/9/21",
    changer: "佐藤\u3000匡",
    department: "BPO推進部",
    work: "帳票汚れ検知",
    supportTool: "AI（画像認識）",
    state: "計画・調査中",
    staff: "BPO推進部BPO推進Gr",
    expectedEffect: "検証時間の削減\n",
    effect: "",
    attachedFile: "",
    comment: [],
  },
  {
    id: 50,
    registrationDate: "2021/9/21",
    updateDate: "2021/9/21",
    changer: "山原\u3000豊",
    department: "ビジネス営業部",
    work: "データエントリー業務",
    supportTool: "給報AI-OCR",
    state: "運用中",
    staff: "データエントリーグループ",
    expectedEffect: "工数削減（データ入力業務）",
    effect: "",
    attachedFile: "",
    comment: [],
  },
  {
    id: 51,
    registrationDate: "2021/9/21",
    updateDate: "2021/9/21",
    changer: "山原\u3000豊",
    department: "ビジネス営業部",
    work: "データエントリー業務",
    supportTool: "AI-OCR補完ツール",
    state: "運用中",
    staff: "データエントリーグループ",
    expectedEffect: "工数削減（データ入力業務）",
    effect: "",
    attachedFile: "",
    comment: [],
  },
  {
    id: 52,
    registrationDate: "2021/9/21",
    updateDate: "2021/9/21",
    changer: "大坊\u3000亮一",
    department: "BPO推進部",
    work: "大分県運用保守",
    supportTool: "月報excel化",
    state: "運用中",
    staff: "システムサービスグループ",
    expectedEffect:
      "毎月月初に客先に提出している月報の様式をword⇒excelに変える事で、作業時間の集計を自動化し、月報作成時間の短縮を図る",
    effect: "中",
    attachedFile: "",
    comment: [],
  },
  {
    id: 53,
    registrationDate: "2021/9/21",
    updateDate: "2022/1/5",
    changer: "安森\u3000雅子",
    department: "BPO推進部",
    work: "SE日報入力",
    supportTool: "SE日報入力簡略化",
    state: "運用中",
    staff: "システムサービスグループ",
    expectedEffect:
      "SE日報に取り込みが出来る、CSVファイルを吐き出すツールを作成し、SE日報の入力時間の削減、共有PCの利用時間の短縮を図る\n\n当初、社員だけを対象としていたが、現在は、臨時社員、外注社員を含めて運用している。",
    effect: "大",
    attachedFile: "",
    comment: [],
  },
  {
    id: 54,
    registrationDate: "2021/9/21",
    updateDate: "2022/1/5",
    changer: "安森\u3000雅子",
    department: "BPO推進部",
    work: "大分県ヘルプデスク",
    supportTool: "AI-FAQの活用",
    state: "計画・調査中",
    staff: "システムサービスグループ",
    expectedEffect: "ヘルプデスクへの問い合わせ件数減、業務効率化を図る",
    effect: "",
    attachedFile: "",
    comment: [],
  },
  {
    id: 55,
    registrationDate: "2021/9/21",
    updateDate: "2021/9/21",
    changer: "後藤\u3000恵",
    department: "人事部",
    work: "通勤費データ(月末処理)",
    supportTool: "Excel",
    state: "計画・調査中",
    staff: "伊藤理事",
    expectedEffect: "通勤費デー タ(財務部送付分)の作成を自動化。",
    effect: "",
    attachedFile: "",
    comment: [],
  },
  {
    id: 56,
    registrationDate: "2021/9/21",
    updateDate: "2021/9/21",
    changer: "高熊\u3000洋子",
    department: "東京本社マネジメント推進部",
    work: "東京本社入室鍵管理",
    supportTool: "サイボウズ、Excel",
    state: "運用中",
    staff: "東京本社マネジメント推進部",
    expectedEffect: "ペーパーレス化、作業効率改善",
    effect: "中",
    attachedFile: "",
    comment: [],
  },
  {
    id: 57,
    registrationDate: "2021/9/21",
    updateDate: "2021/10/7",
    changer: "高熊\u3000洋子",
    department: "東京本社マネジメント推進部",
    work: "記録メディア運用管理",
    supportTool: "サイボウズ、Excel",
    state: "運用中",
    staff: "東京本社マネジメント推進部",
    expectedEffect: "ペーパーレス化、作業効率改善",
    effect: "",
    attachedFile: "",
    comment: [],
  },
  {
    id: 58,
    registrationDate: "2021/9/22",
    updateDate: "2021/9/22",
    changer: "佐藤亜紀",
    department: "総務部",
    work: " 各種社内募集業務（無料チケット配布・ワクチン接種申込等）",
    supportTool: "サイボウズ",
    state: "運用中",
    staff: "総務部",
    expectedEffect:
      "各種社内募集・申込（無料チケット配布・ワクチン接種希望者）をサイボウズメールからワークフローへ変更した。申込内 容がデータ化され業務効率化に繋がった",
    effect: "中",
    attachedFile: "",
    comment: [],
  },
  {
    id: 59,
    registrationDate: "2021/9/22",
    updateDate: "2021/9/22",
    changer: "佐藤亜紀",
    department: "総務部",
    work: " 社内問い合わせ対応",
    supportTool: "チャットボット",
    state: "運用中",
    staff: "総務部",
    expectedEffect:
      "社内からの問い合 わせ対応をチャットボットで行う事により、業務の効率化を図る",
    effect: "中",
    attachedFile: "",
    comment: [],
  },
  {
    id: 60,
    registrationDate: "2021/9/22",
    updateDate: "2021/11/1",
    changer: "佐藤亜紀",
    department: "総務部",
    work: " 郵便業務",
    supportTool: "郵便料金計器導入",
    state: "運用中",
    staff: "杉﨑綾香",
    expectedEffect:
      "郵便発送業務の作業効率 化による、工数削減。及び、手作業による入力ミス・計量ミスの防止等。",
    effect: "中",
    attachedFile: "",
    comment: [],
  },
  {
    id: 61,
    registrationDate: "2021/9/24",
    updateDate: "2021/9/24",
    changer: "佐藤亜紀",
    department: "総務部",
    work: " 事故違反事例\u3000データベース",
    supportTool: "サイボウズ",
    state: "運用中",
    staff: "上野佐智子",
    expectedEffect:
      "社内 で起きた交通事故違反事例をデータベース化する事により、日頃どのような事故・違反が、どのような場面で起こっているかを知り、分析する事が出来、今後の予防にも繋がる。\n",
    effect: "中",
    attachedFile: "",
    comment: [],
  },
  {
    id: 62,
    registrationDate: "2021/9/28",
    updateDate: "2021/9/28",
    changer: "南\u3000百香",
    department: "公共ソリューション部",
    work: "プロジェクト管理",
    supportTool: "POWER EGG,redmine,backlog",
    state: "運用中",
    staff: "公共ソリューション部",
    expectedEffect: "ペーパーレス化",
    effect: "中",
    attachedFile: "",
    comment: [],
  },
  {
    id: 63,
    registrationDate: "2021/9/28",
    updateDate: "2021/9/28",
    changer: "南\u3000百香",
    department: "公共ソリューション部",
    work: "大分県人事管理システム運用保守",
    supportTool: "Excel",
    state: "運用中",
    staff: "公共ソリューション部",
    expectedEffect: "出荷の作業効率改善",
    effect: "中",
    attachedFile: "",
    comment: [],
  },
  {
    id: 64,
    registrationDate: "2021/9/28",
    updateDate: "2021/9/28",
    changer: "南\u3000百香",
    department: "公共ソリューション部",
    work: "ｅＧ-モデル運用支援",
    supportTool: "C#",
    state: "運用中",
    staff: "ソリューション導入グループ",
    expectedEffect: "出荷の作業効率改善",
    effect: "中",
    attachedFile: "",
    comment: [],
  },
  {
    id: 65,
    registrationDate: "2021/9/28",
    updateDate: "2021/9/28",
    changer: "佐藤亜紀",
    department: "総務部",
    work: " 安全衛生委員会",
    supportTool: "サイボウズ",
    state: "運用中",
    staff: "上野佐智子",
    expectedEffect:
      "安全衛生委員会におけ る報告書（７種類）の提出を、ワークフロー化した。ペーパーレス化及び業務効率の改善につながった。",
    effect: "中",
    attachedFile: "",
    comment: [],
  },
  {
    id: 66,
    registrationDate: "2021/10/4",
    updateDate: "2021/10/4",
    changer: "",
    department: "施設予約サービス部",
    work: "部内業務全般",
    supportTool: "POWEREGG、サイボウズ",
    state: "運用中",
    staff: "木下",
    expectedEffect:
      "紙運用していた書類24種類のうち21種類をペーパレス運用に切り替えた。これにより、社内の申請・承認手続きの遅延、運用書類保管場所の不足などの生産性の低下、紙の消費による環境への負荷、テレワークへの推進へ対応した。",
    effect: "中",
    attachedFile: "",
    comment: [],
  },
  {
    id: 67,
    registrationDate: "2021/10/4",
    updateDate: "2021/10/4",
    changer: "",
    department: "施設予約サービス部",
    work: "施設予約導入業務",
    supportTool: "Power Automate等",
    state: "運用中",
    staff: "緒方健",
    expectedEffect:
      "導入時の作業に必要な業務の一部をRPA化することにより、単純作業の自動化を行った。これにより、業務効率化に繋がる。",
    effect: "中",
    attachedFile: "",
    comment: [],
  },
  {
    id: 68,
    registrationDate: "2021/6/1",
    updateDate: "2021/10/12",
    changer: "佐藤亜紀",
    department: "総務部",
    work: " 郵便業務（書留・簡易書留・特定記録受領確認）",
    supportTool: "サイボウズ",
    state: "運用中",
    staff: "杉﨑綾香",
    expectedEffect: "ペーパーレス化・紛失防止・作業効率改善等",
    effect: "中",
    attachedFile: "",
    comment: [],
  },
  {
    id: 69,
    registrationDate: "2021/10/26",
    updateDate: "2021/10/26",
    changer: "",
    department: "施設予約サービス部",
    work: "施設予約運用・保守",
    supportTool: "マクロ",
    state: "運用中",
    staff: "施設予約運用グループ",
    expectedEffect:
      "出荷時のISO資料作成時にマクロを利用して、定型化できる部分を定型化している。\n平準化ができ、誰でも作業できるようになっている。",
    effect: "中",
    attachedFile: "",
    comment: [],
  },
  {
    id: 70,
    registrationDate: "2021/10/26",
    updateDate: "2021/10/26",
    changer: "",
    department: "施設予約サービス部",
    work: "施設予約導入業務",
    supportTool: "Redmine",
    state: "運用中",
    staff: "施設予約運用グループ",
    expectedEffect:
      "お客様 とのやりとりをメールではなく、Redmineのチケットを使ってやりとりを行う。\nメール内容をチケット化する手間などの軽減とお客様との情 報共有がスムーズに\n行なえるようになっている。",
    effect: "中",
    attachedFile: "",
    comment: [],
  },
  {
    id: 71,
    registrationDate: "2021/11/2",
    updateDate: "2021/11/2",
    changer: "",
    department: "ソリューション開発部",
    work: "プロジェクト管理全般",
    supportTool: "OBPM Neo",
    state: "準備・検証中",
    staff: "パッケージ導入運用グループ",
    expectedEffect:
      "・「OBPM Neo」には以下の特長があり、利用することでこれらのことが従来PMの手腕や経験に左右されていたプロジェクトマネジメント手法の標準化が期待できる。\n\u3000①部門や製品、開発手法などプロジェクトタイプに応じたＷＢＳや品質基準、進捗基準、レビューパ ターン等の標準パターンをドメイン機能でテンプレート化することができる。\n\u3000②個別のプロジェクト管理はもちろんのこと、部門で抱 える複数のプロジェクトのコストや進捗、要員状況をリアルタイムで把握し、会社で抱える全てのプロジェクトを一元管理することができる。\n\u3000③計画、プロジェクト実行、状況把握、経営活用といった一般的なプロジェクト管理業務のサイクルで実施するべき内容をOBPM Neoで 統合的に管理することができ、従来バラバラに管理されていたプロジェクト管理を全社共通の指標で統合管理できるためプロジェクト品質・生産性の向上、見える化につながる。",
    effect: "",
    attachedFile: "",
    comment: [],
  },
  {
    id: 72,
    registrationDate: "2021/11/2",
    updateDate: "2021/11/2",
    changer: "",
    department: "ソリューション開発部",
    work: "施設予約運用保守業務",
    supportTool: "Redmine",
    state: "運用中",
    staff: "パッケージ導入運用グループ",
    expectedEffect:
      "お客様とのやりとりをメールではなく、Redmineのチケットを使ってやりとりを行う。\nメール内容をチケット化する手間などの軽減とお客様との情報共有がスムーズに\n行なえるようになっている",
    effect: "中",
    attachedFile: "",
    comment: [],
  },
  {
    id: 73,
    registrationDate: "2021/11/2",
    updateDate: "2021/11/2",
    changer: "",
    department: "ソリューション開発部",
    work: "東松山市eG-モデルリプレース業務",
    supportTool: "Slack",
    state: "準備・検証中",
    staff: "システムインテグレーショングループ",
    expectedEffect:
      "プロジェクトにおけるメンバー間とのやりとりをメールや口頭だけではなく、Slackを使って行う。\n課題の共有 や伝達事項の徹底、テレワークにおけるコミュニケーション強化などの効果が期待できる。",
    effect: "",
    attachedFile: "",
    comment: [],
  },
  {
    id: 74,
    registrationDate: "2022/1/18",
    updateDate: "2022/1/18",
    changer: "佐藤亜紀",
    department: "総務部",
    work: " 受付業務日誌",
    supportTool: "サイボウズ",
    state: "運用中",
    staff: "杉﨑綾香",
    expectedEffect: "ペーパーレス化、業務改善",
    effect: "中",
    attachedFile: "",
    comment: [],
  },
  {
    id: 75,
    registrationDate: "2022/1/19",
    updateDate: "2022/1/19",
    changer: "永野\u3000聡",
    department: "西日本支社",
    work: "全般",
    supportTool: "Webex Teams",
    state: "運用中",
    staff: "江隈\u3000慎太郎",
    expectedEffect:
      "勤務地を問わず即 時性の高いコミュニケーションツールとして活用できる。（メッセージ、通話）",
    effect: "中",
    attachedFile: "",
    comment: [],
  },
  {
    id: 76,
    registrationDate: "2022/1/19",
    updateDate: "2022/1/19",
    changer: "永野\u3000聡",
    department: "西日本支社",
    work: "三重県教職員人事システム",
    supportTool: "Webex Teams、Backlog、ServiceNow",
    state: "運用中",
    staff: "小野\u3000万尚",
    expectedEffect:
      "Backlogの課題追加、コメント追加をServiceNowを用いてWebex Teamsに連携することで連絡事項の即時性が高まり確認漏れの防止につながる。また、UIが集約され作業効率の向上につながる。",
    effect: "中",
    attachedFile: "",
    comment: [],
  },
  {
    id: 77,
    registrationDate: "2022/1/19",
    updateDate: "2022/1/19",
    changer: "永野\u3000聡",
    department: "西日本支社",
    work: "京都府財務システム運用保守",
    supportTool: "Backlog",
    state: "運用中",
    staff: "渕上\u3000洋貴",
    expectedEffect:
      " 課題管理の方法をExcelからBacklogに変更。担当者への通知やコメント、資料の添付によって、効率的なコミュニケーションが可能になった。",
    effect: "中",
    attachedFile: "",
    comment: [],
  },
  {
    id: 78,
    registrationDate: "2022/1/19",
    updateDate: "2022/1/19",
    changer: "永野\u3000聡",
    department: "西日本支社",
    work: "人事給与システム運用保守",
    supportTool: "Power Automate Desktop",
    state: "運用中",
    staff: "和田\u3000悠登",
    expectedEffect:
      "客先に送付するバッチファイル作成やメール作成などの作業を自動化。作業時間と人的ミスの削減につながった。",
    effect: "中",
    attachedFile: "",
    comment: [],
  },
  {
    id: 79,
    registrationDate: "2022/2/24",
    updateDate: "2022/2/24",
    changer: "相川真理子",
    department: "経営戦略部",
    work: "議事録作成",
    supportTool: "AutoMemo（オートメモ）Sホワイト AWSWH",
    state: "運用見送り",
    staff: "相川真理子",
    expectedEffect:
      "議事録作成時間の削減\n\n運用見送り\n・文字おこしの精度は思ったより良かったが、長文が並んでおり、読みづらい。誰が発言 したかがわからない。\n・編集ｿﾌﾄがｽﾏﾎｱﾌﾟﾘ対応していて、PCでは対応していない。\n・appleIDが必要で、手続きが面倒。",
    effect: "--",
    attachedFile: "",
    comment: [],
  },
  {
    id: 80,
    registrationDate: "2022/3/14",
    updateDate: "2022/3/14",
    changer: "森脇毅",
    department: "経営戦略部",
    work: "プロジェクト管理表提出（毎月上旬）のペーパーレス化",
    supportTool: "",
    state: "準備・検証中",
    staff: "森脇",
    expectedEffect:
      "・用紙使用量の削減\n・プロジェクト管理表の経営戦略部への提出の効率化",
    effect: "",
    attachedFile: "",
    comment: [],
  },
  {
    id: 81,
    registrationDate: "2022/3/15",
    updateDate: "2022/3/15",
    changer: "首藤\u3000乃布枝",
    department: "財務部",
    work: "買掛業務（外注費計上処理）業務の改善",
    supportTool: "BillOne、Excel",
    state: "運用中",
    staff: "金江、財務部",
    expectedEffect:
      "BillOneデータを利用することで請求書のペーパレス化、経費計上の仕訳データを自動化して業務の効率化を図る",
    effect: "中",
    attachedFile: "",
    comment: [],
  },
  {
    id: 82,
    registrationDate: "2022/9/15",
    updateDate: "2022/9/15",
    changer: "山本\u3000修",
    department: "ソリューションサービス部",
    work: "案件管理（予算管理）",
    supportTool: "案件管理システム",
    state: "運用中",
    staff: "山本\u3000修",
    expectedEffect:
      "・日々の案件状況（売上月、支払月、受注状況確認）\n・月々の売上計上の確認、外注費の請求確認\n・月々の予算実績表\u3000更新の精度及び作業生産性の向上\n・案件・予算管理のルーチンワーク化",
    effect: "大",
    attachedFile: "",
    comment: [],
  },
  {
    id: 83,
    registrationDate: "2022/9/15",
    updateDate: "2022/9/15",
    changer: "山本\u3000修",
    department: "ソリューションサービス部",
    work: "要員管理",
    supportTool: "要員管理ツール",
    state: "運用中",
    staff: "山本・阿南",
    expectedEffect:
      " ・個人毎、プロジェクト毎のWBSをサマリーし、個人毎の作業負荷状況が見える化できる\n・計画だけでなく、SE日報と連携し、実績の集計が でき、ＰＪの状況悪化や負荷分散の検討を行うインプットとして利用できる。",
    effect: "中",
    attachedFile: "",
    comment: [],
  },
];

export default datas;
